const APP_ID = "<APP_ID>";
const API_TOKEN = "<API_TOKEN>";
const USER_LIMIT = 10;
const GDPR_REQUEST_LIMIT = 100;
const REQUEST_THROTTLING_TIMEOUT = 10000;
const CSV_FILE_PATH = "./data.csv";

module.exports = {
  APP_ID,
  API_TOKEN,
  USER_LIMIT,
  GDPR_REQUEST_LIMIT,
  REQUEST_THROTTLING_TIMEOUT,
  CSV_FILE_PATH
}