const path = require('path')
const APP_ID = "<YOUR APP ID HERE>";
const API_TOKEN = "<YOUR API TOKEN HERE>";
const USER_LIMIT = 100;
const GDPR_REQUEST_LIMIT = 100;
const REQUEST_THROTTLING_TIMEOUT = 1500;
const JSON_FILENAME = 'export-requests.json'
const JSON_FILE_PATH = path.join(__dirname, JSON_FILENAME)
const COMPLETED_REQUESTS_FILENAME = 'completed-requests.json'
const COMPLETED_REQUESTS_FILE_PATH = path.join(__dirname, COMPLETED_REQUESTS_FILENAME)
const COMPLETED_REQUESTS_CSV_FILENAME = 'completed-requests.csv'
const COMPLETED_REQUESTS_CSV_FILE_PATH = path.join(__dirname, COMPLETED_REQUESTS_CSV_FILENAME)

module.exports = {
  APP_ID,
  API_TOKEN,
  USER_LIMIT,
  GDPR_REQUEST_LIMIT,
  REQUEST_THROTTLING_TIMEOUT,
  JSON_FILE_PATH,
  JSON_FILENAME,
  COMPLETED_REQUESTS_FILENAME,
  COMPLETED_REQUESTS_FILE_PATH,
  COMPLETED_REQUESTS_CSV_FILENAME,
  COMPLETED_REQUESTS_CSV_FILE_PATH
}